import json

def md_cell(text: str):
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [l for l in text.splitlines(keepends=True)]
    }

def code_cell(text: str):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [l for l in text.splitlines(keepends=True)]
    }

md_intro = (
    "# K Training Notebook (replicates train.py)\n\n"
    "Self-contained version: all configuration lives in this notebook.\n"
    "Supports multiple datasets by setting RAW_DATASET_NAME to a list.\n"
)

cells = []
cells.append(md_cell(md_intro))

cells.append(code_cell(
    "# Optional: install dependencies (uncomment as needed)\n"
    "# %pip install -U unsloth datasets trl peft transformers accelerate einops bitsandbytes python-dotenv matplotlib pandas huggingface_hub\n"
))

cells.append(code_cell(
    "# Imports and inline configuration\n"
    "import os, csv, glob\n"
    "from datetime import datetime\n"
    "import torch\n"
    "import matplotlib.pyplot as plt\n"
    "import pandas as pd\n"
    "from datasets import load_dataset, concatenate_datasets\n"
    "from transformers import TrainerCallback\n"
    "from trl import SFTTrainer, SFTConfig\n"
    "from unsloth import FastModel\n"
    "from unsloth.chat_templates import get_chat_template, train_on_responses_only\n"
    "\n"
    "# Load .env if available\n"
    "try:\n"
    "    from dotenv import load_dotenv\n"
    "    load_dotenv()\n"
    "    print('Loaded environment from .env')\n"
    "except Exception:\n"
    "    pass\n"
    "\n"
    "# Torch/inductor safety for older GPUs (replicates train.py)\n"
    "os.environ['TORCH_USE_CUDA_DSA'] = '1'\n"
    "os.environ['CUDA_LAUNCH_BLOCKING'] = '1'\n"
    "os.environ['TORCH_INDUCTOR'] = '0'\n"
    "os.environ['TORCHINDUCTOR_MAX_AUTOTUNE'] = '0'\n"
    "os.environ['TORCH_COMPILE_DISABLE'] = '1'\n"
    "os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'\n"
    "\n"
    "# Disable dynamo paths like in train.py\n"
    "try:\n"
    "    torch._dynamo.config.suppress_errors = True\n"
    "    torch._dynamo.reset()\n"
    "    torch._dynamo.config.disable = True\n"
    "except Exception:\n"
    "    pass\n"
    "\n"
    "# =====================\n"
    "# Inline configuration\n"
    "# =====================\n"
    "HUB_MODEL_NAME  = 'ThomasTheMaker/k-1b'\n"
    "MODEL_NAME      = 'unsloth/gemma-3-1b-it-unsloth-bnb-4bit'\n"
    "MAX_SEQ_LENGTH  = 1024\n"
    "LOAD_IN_4BIT    = True\n"
    "LOAD_IN_8BIT    = False\n"
    "FULL_FINETUNING = False\n"
    "\n"
    "# Multiple datasets supported: list of strings\n"
    "RAW_DATASET_NAME = ['ThomasTheMaker/Synthetic-Object-v0']  # add more names here\n"
    "DATASET_SPLIT    = 'train'\n"
    "CHAT_TEMPLATE    = 'gemma3'\n"
    "\n"
    "# LoRA configuration\n"
    "LORA_R       = 32\n"
    "LORA_ALPHA   = LORA_R * 2\n"
    "LORA_DROPOUT = 0.05\n"
    "LORA_BIAS    = 'none'\n"
    "USE_GRADIENT_CHECKPOINTING = 'unsloth'\n"
    "RANDOM_STATE  = 3407\n"
    "USE_RSLORA    = False\n"
    "LOFTQ_CONFIG  = None\n"
    "TARGET_MODULES= ['q_proj','k_proj','v_proj','o_proj','gate_proj','up_proj','down_proj']\n"
    "\n"
    "# Training configuration\n"
    "PER_DEVICE_TRAIN_BATCH_SIZE = 2\n"
    "GRADIENT_ACCUMULATION_STEPS = 8\n"
    "WARMUP_STEPS                = 5\n"
    "MAX_STEPS                   = -1\n"
    "NUM_TRAIN_EPOCHS            = 3\n"
    "LEARNING_RATE               = 3e-5\n"
    "WEIGHT_DECAY                = 0.01\n"
    "LR_SCHEDULER_TYPE           = 'linear'\n"
    "SEED                        = 3407\n"
    "OUTPUT_DIR                  = 'outputs'\n"
    "REPORT_TO                   = 'none'\n"
    "OPTIM                       = 'adamw_8bit'\n"
    "LOGGING_STEPS               = 1\n"
    "SAVE_STRATEGY               = 'steps'\n"
    "SAVE_STEPS                  = 300\n"
    "SAVE_TOTAL_LIMIT            = 3\n"
    "EVAL_STRATEGY               = 'no'\n"
    "EVAL_STEPS                  = 1000\n"
    "\n"
    "# Inference and saving\n"
    "GEN_MAX_NEW_TOKENS = 1024\n"
    "GEN_TEMPERATURE    = 0.8\n"
    "GEN_TOP_P          = 0.95\n"
    "GEN_TOP_K          = 64\n"
    "GEN_DO_SAMPLE      = True\n"
    "\n"
    "SAVE_LOCAL = True\n"
    "SAVE_16BIT = True\n"
    "SAVE_4BIT  = False\n"
    "SAVE_LORA = True\n"
    "PUSH_TO_HUB = True\n"
    "\n"
    "CSV_LOG_ENABLED = True\n"
    "CSV_LOG_FILE = f'{HUB_MODEL_NAME}/training_metrics.csv'\n"
    "CSV_PLOT_FILE = f'{HUB_MODEL_NAME}/training_metrics.png'\n"
    "\n"
    "os.makedirs(HUB_MODEL_NAME, exist_ok=True)\n"
))

cells.append(code_cell(
    "# CSV logging callback\n"
    "class CSVMetricsCallback(TrainerCallback):\n"
    "    def __init__(self, csv_file_path):\n"
    "        self.csv_file_path = csv_file_path\n"
    "        self.metrics_data = []\n"
    "        self.fieldnames = ['step', 'epoch', 'loss', 'grad_norm', 'learning_rate', 'timestamp']\n"
    "        with open(csv_file_path, 'w', newline='') as csvfile:\n"
    "            writer = csv.DictWriter(csvfile, fieldnames=self.fieldnames)\n"
    "            writer.writeheader()\n"
    "    def on_log(self, args, state, control, model=None, logs=None, **kwargs):\n"
    "        if logs is not None and CSV_LOG_ENABLED:\n"
    "            metrics = {\n"
    "                'step': state.global_step,\n"
    "                'epoch': logs.get('epoch', 0),\n"
    "                'loss': logs.get('loss', None),\n"
    "                'grad_norm': logs.get('grad_norm', None),\n"
    "                'learning_rate': logs.get('learning_rate', None),\n"
    "                'timestamp': datetime.now().isoformat(),\n"
    "            }\n"
    "            if any(v is not None for v in [metrics['loss'], metrics['grad_norm'], metrics['learning_rate']]):\n"
    "                self.metrics_data.append(metrics)\n"
    "                with open(self.csv_file_path, 'a', newline='') as csvfile:\n"
    "                    writer = csv.DictWriter(csvfile, fieldnames=self.fieldnames)\n"
    "                    writer.writerow(metrics)\n"
    "                print(f\"Logged metrics: Step {metrics['step']}, Loss: {metrics['loss']}, LR: {metrics['learning_rate']}\")\n"
    "    def on_train_end(self, args, state, control, **kwargs):\n"
    "        if CSV_LOG_ENABLED:\n"
    "            print(f'\\nTraining metrics saved to: {self.csv_file_path}')\n"
    "            print(f'Total logged entries: {len(self.metrics_data)}')\n"
))

cells.append(code_cell(
    "# Load model and attach LoRA\n"
    "model, tokenizer = FastModel.from_pretrained(\n"
    "    model_name=MODEL_NAME,\n"
    "    max_seq_length=MAX_SEQ_LENGTH,\n"
    "    load_in_4bit=LOAD_IN_4BIT,\n"
    "    load_in_8bit=LOAD_IN_8BIT,\n"
    "    full_finetuning=FULL_FINETUNING,\n"
    ")\n"
    "model = FastModel.get_peft_model(\n"
    "    model,\n"
    "    r=LORA_R,\n"
    "    target_modules=TARGET_MODULES,\n"
    "    lora_alpha=LORA_ALPHA,\n"
    "    lora_dropout=LORA_DROPOUT,\n"
    "    bias=LORA_BIAS,\n"
    "    use_gradient_checkpointing=USE_GRADIENT_CHECKPOINTING,\n"
    "    random_state=RANDOM_STATE,\n"
    "    use_rslora=USE_RSLORA,\n"
    "    loftq_config=LOFTQ_CONFIG,\n"
    ")\n"
    "tokenizer = get_chat_template(tokenizer, chat_template=CHAT_TEMPLATE)\n"
    "print('Model and tokenizer loaded; LoRA configured.')\n"
))

cells.append(code_cell(
    "# Dataset loading with multi-dataset support\n"
    "from typing import List\n"
    "def to_list(x) -> List[str]:\n"
    "    if isinstance(x, str):\n"
    "        return [x]\n"
    "    if isinstance(x, (list, tuple)):\n"
    "        return list(x)\n"
    "    raise ValueError('RAW_DATASET_NAME must be a string or list of strings')\n"
    "\n"
    "dataset_names = to_list(RAW_DATASET_NAME)\n"
    "print('Datasets:', dataset_names)\n"
    "loaded = []\n"
    "for name in dataset_names:\n"
    "    print(f'Loading dataset: {name} (split={DATASET_SPLIT})')\n"
    "    ds = load_dataset(name, split=DATASET_SPLIT)\n"
    "    loaded.append(ds)\n"
    "dataset = loaded[0] if len(loaded)==1 else concatenate_datasets(loaded)\n"
    "dataset = dataset.train_test_split(test_size=0.05, seed=SEED)\n"
    "train_dataset, eval_dataset = dataset['train'], dataset['test']\n"
    "print(f'Training samples: {len(train_dataset)}, Validation samples: {len(eval_dataset)}')\n"
    "\n"
    "def convert_to_chatml(example):\n"
    "    return {\n"
    "        'conversations': [\n"
    "            {'role': 'user', 'content': 'hey cadmonkey, create me a ' + example['name']},\n"
    "            {'role': 'assistant', 'content': example['code']},\n"
    "        ]\n"
    "    }\n"
    "train_dataset = train_dataset.map(convert_to_chatml)\n"
    "eval_dataset  = eval_dataset.map(convert_to_chatml)\n"
    "\n"
    "def formatting_prompts_func(examples):\n"
    "    convos = examples['conversations']\n"
    "    texts = [tokenizer.apply_chat_template(c, tokenize=False, add_generation_prompt=False).removeprefix('<bos>') for c in convos]\n"
    "    return {'text': texts}\n"
    "train_dataset = train_dataset.map(formatting_prompts_func, batched=True)\n"
    "eval_dataset  = eval_dataset.map(formatting_prompts_func, batched=True)\n"
    "print('Preview example text:')\n"
    "print(train_dataset[0]['text'][:200], '...')\n"
))

cells.append(code_cell(
    "# Trainer setup and training (resume if checkpoints exist)\n"
    "csv_callback = CSVMetricsCallback(CSV_LOG_FILE) if CSV_LOG_ENABLED else None\n"
    "training_args = {\n"
    "    'dataset_text_field': 'text',\n"
    "    'per_device_train_batch_size': PER_DEVICE_TRAIN_BATCH_SIZE,\n"
    "    'gradient_accumulation_steps': GRADIENT_ACCUMULATION_STEPS,\n"
    "    'warmup_steps': WARMUP_STEPS,\n"
    "    'learning_rate': LEARNING_RATE,\n"
    "    'logging_steps': LOGGING_STEPS,\n"
    "    'optim': OPTIM,\n"
    "    'weight_decay': WEIGHT_DECAY,\n"
    "    'lr_scheduler_type': LR_SCHEDULER_TYPE,\n"
    "    'seed': SEED,\n"
    "    'output_dir': OUTPUT_DIR,\n"
    "    'report_to': REPORT_TO,\n"
    "    'save_strategy': SAVE_STRATEGY,\n"
    "    'save_steps': SAVE_STEPS,\n"
    "    'save_total_limit': SAVE_TOTAL_LIMIT,\n"
    "    'eval_strategy': EVAL_STRATEGY,\n"
    "    'eval_steps': EVAL_STEPS,\n"
    "}\n"
    "if MAX_STEPS and MAX_STEPS > 0:\n"
    "    training_args['max_steps'] = MAX_STEPS\n"
    "else:\n"
    "    training_args['num_train_epochs'] = NUM_TRAIN_EPOCHS\n"
    "trainer = SFTTrainer(\n"
    "    model=model,\n"
    "    tokenizer=tokenizer,\n"
    "    train_dataset=train_dataset,\n"
    "    eval_dataset=eval_dataset,\n"
    "    args=SFTConfig(**training_args),\n"
    ")\n"
    "if csv_callback:\n"
    "    trainer.add_callback(csv_callback)\n"
    "trainer = train_on_responses_only(\n"
    "    trainer,\n"
    "    instruction_part='<start_of_turn>user\n',\n"
    "    response_part='<start_of_turn>model\n',\n"
    ")\n"
    "gpu_props = torch.cuda.get_device_properties(0) if torch.cuda.is_available() else None\n"
    "if gpu_props:\n"
    "    start_gpu_memory = round(torch.cuda.max_memory_reserved()/1024/1024/1024, 3)\n"
    "    max_memory = round(gpu_props.total_memory/1024/1024/1024, 3)\n"
    "    print(f'GPU = {gpu_props.name}. Max memory = {max_memory} GB.')\n"
    "    print(f'{start_gpu_memory} GB of memory reserved.')\n"
    "checkpoints = glob.glob(f'{OUTPUT_DIR}/checkpoint-*')\n"
    "resume_from_checkpoint = None\n"
    "if checkpoints:\n"
    "    latest = max(checkpoints, key=lambda x: int(x.split('-')[-1]))\n"
    "    resume_from_checkpoint = latest\n"
    "    print('Resuming from', resume_from_checkpoint)\n"
    "else:\n"
    "    print('No checkpoints found; training from scratch.')\n"
    "trainer_stats = trainer.train(resume_from_checkpoint=resume_from_checkpoint)\n"
    "print(f'Training time (s): {trainer_stats.metrics.get(\'train_runtime\')}')\n"
))

cells.append(code_cell(
    "# Metrics summary + plot (if CSV exists)\n"
    "import os\n"
    "if os.path.exists(CSV_LOG_FILE):\n"
    "    df = pd.read_csv(CSV_LOG_FILE)\n"
    "    if len(df) > 0:\n"
    "        print('Total logged steps:', len(df))\n"
    "        if 'loss' in df.columns and df['loss'].notna().any():\n"
    "            losses = df['loss'].dropna()\n"
    "            print('Final Loss:', round(losses.iloc[-1], 4))\n"
    "        fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n"
    "        fig.suptitle('Training Metrics', fontsize=16, fontweight='bold')\n"
    "        if 'loss' in df.columns and df['loss'].notna().any():\n"
    "            axes[0,0].plot(df['step'], df['loss'], color='#e74c3c')\n"
    "            axes[0,0].set_title('Loss')\n"
    "        if 'learning_rate' in df.columns and df['learning_rate'].notna().any():\n"
    "            axes[0,1].plot(df['step'], df['learning_rate'], color='#3498db')\n"
    "            axes[0,1].set_title('Learning Rate')\n"
    "        if 'grad_norm' in df.columns and df['grad_norm'].notna().any():\n"
    "            axes[1,0].plot(df['step'], df['grad_norm'], color='#2ecc71')\n"
    "            axes[1,0].set_title('Gradient Norm')\n"
    "        if 'epoch' in df.columns and 'loss' in df.columns and df['loss'].notna().any():\n"
    "            axes[1,1].plot(df['epoch'], df['loss'], color='#9b59b6')\n"
    "            axes[1,1].set_title('Loss per Epoch')\n"
    "        plt.tight_layout()\n"
    "        plt.savefig(CSV_PLOT_FILE, dpi=300, bbox_inches='tight')\n"
    "        print('Saved plot to', CSV_PLOT_FILE)\n"
    "else:\n"
    "    print('No CSV metrics file found at', CSV_LOG_FILE)\n"
))

cells.append(code_cell(
    "# Quick generation test\n"
    "system_prompt = 'You are a helpful CAD assistant.'\n"
    "user_prompt   = 'Create me a simple parametric cube in OpenSCAD.'\n"
    "messages = [\n"
    "    {'role': 'system', 'content': system_prompt},\n"
    "    {'role': 'user',   'content': user_prompt},\n"
    "]\n"
    "text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)\n"
    "inputs = tokenizer(text, return_tensors='pt').to(model.device)\n"
    "with torch.inference_mode():\n"
    "    outputs = model.generate(**inputs,\n"
    "        max_new_tokens=GEN_MAX_NEW_TOKENS,\n"
    "        temperature=GEN_TEMPERATURE,\n"
    "        top_p=GEN_TOP_P,\n"
    "        top_k=GEN_TOP_K,\n"
    "        do_sample=GEN_DO_SAMPLE,\n"
    "        use_cache=False,\n"
    "    )\n"
    "print('Generated response:\\n', tokenizer.decode(outputs[0], skip_special_tokens=True))\n"
))

cells.append(code_cell(
    "# Saving: LoRA adapters and 16-bit merged model, optional push to Hub\n"
    "hf_token = os.getenv('HF_TOKEN')\n"
    "if SAVE_LORA:\n"
    "    print('Saving LoRA adapters...')\n"
    "    if SAVE_LOCAL:\n"
    "        model.save_pretrained(HUB_MODEL_NAME)\n"
    "        tokenizer.save_pretrained(HUB_MODEL_NAME)\n"
    "        print('Saved locally to', HUB_MODEL_NAME)\n"
    "    if PUSH_TO_HUB and hf_token:\n"
    "        model.push_to_hub(HUB_MODEL_NAME, token=hf_token)\n"
    "        tokenizer.push_to_hub(HUB_MODEL_NAME, token=hf_token)\n"
    "        print('Pushed LoRA to HF Hub at', f'https://huggingface.co/{HUB_MODEL_NAME}')\n"
    "if SAVE_16BIT:\n"
    "    print('Saving 16-bit merged model...')\n"
    "    local_16 = f'{HUB_MODEL_NAME}_16bit'\n"
    "    model.save_pretrained_merged(local_16, tokenizer, save_method='merged_16bit')\n"
    "    print('Saved 16-bit to', local_16)\n"
    "    if PUSH_TO_HUB and hf_token:\n"
    "        print('Uploading 16-bit merged model to Hub at', HUB_MODEL_NAME)\n"
    "        model.push_to_hub_merged(HUB_MODEL_NAME, tokenizer, save_method='merged_16bit', token=hf_token)\n"
    "        try:\n"
    "            from huggingface_hub import HfApi\n"
    "            api = HfApi()\n"
    "            if os.path.exists(CSV_LOG_FILE):\n"
    "                api.upload_file(path_or_fileobj=CSV_LOG_FILE, path_in_repo='training_metrics.csv', repo_id=HUB_MODEL_NAME, token=hf_token)\n"
    "            if os.path.exists(CSV_PLOT_FILE):\n"
    "                api.upload_file(path_or_fileobj=CSV_PLOT_FILE, path_in_repo='training_metrics.png', repo_id=HUB_MODEL_NAME, token=hf_token)\n"
    "            print('Uploaded metrics to Hub repo.')\n"
    "        except Exception as e:\n"
    "            print('Warning: failed to upload metrics:', e)\n"
))

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"}
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

with open('train-cadmonkey.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False)
print('Wrote train-cadmonkey.ipynb')
